In [5]:
import pandas as pd
lista_nomes = "Howard Ian Peter Jonah Kellie" .split()
lista_cpfs = "111.111.111-11 222.222.222-22 333.333.333-33 444.444.444-44 555.555.555-55".split()
lista_emails = "risus.varius@dictumPhasellusin.ca Nunc@vulputate.ca fames.ac.turpis@cursusa.org non@felisullamcorper.org eget.dictum.placerat@necluctus.co.uk".split()
lista_idades = [32, 22, 25, 29, 38]
pd.DataFrame(lista_nomes, columns = ["nome"])

     nome
0  Howard
1     Ian
2   Peter
3   Jonah
4  Kellie

In [8]:
pd.DataFrame(lista_nomes, columns = ["nome"], index = lista_cpfs)

                  nome
111.111.111-11  Howard
222.222.222-22     Ian
333.333.333-33   Peter
444.444.444-44   Jonah
555.555.555-55  Kellie

In [10]:
dados = list(zip(lista_nomes, lista_cpfs, lista_idades, lista_emails))
pd.DataFrame(dados, columns = ["nome", "cpfs", "idade", "email"])

     nome            cpfs  idade                                 email
0  Howard  111.111.111-11     32     risus.varius@dictumPhasellusin.ca
1     Ian  222.222.222-22     22                     Nunc@vulputate.ca
2   Peter  333.333.333-33     25           fames.ac.turpis@cursusa.org
3   Jonah  444.444.444-44     29              non@felisullamcorper.org
4  Kellie  555.555.555-55     38  eget.dictum.placerat@necluctus.co.uk