In [2]:
import pandas as pd
dados = {
    "nomes": "Howard Ian Peter Jonah Kellie".split(),
    "cpfs": "111.111.111-11 222.222.222-22 333.333.333-33 444.444.444-44 555.555.555-55".split(),
    "emails": "risus.varius@dictumPhasellusin.ca Nunc@vulputate.ca fames.ac.turpis@cursusa.org non@felisullamcorper.org eget.dictum.placerat@necluctus.co.uk".split(),
    "idades": [32, 22, 25, 29, 38]
}
pd.DataFrame(dados)

df_dados = pd.DataFrame(dados)
print("\nInformações do DataFrame:\n")
print(df_dados.info())

print("\nQuantidades de linhas e colunas = ", df_dados.shape)
print("\nTipo de dados:\n", df_dados.dtypes)

print("\nQual o menor valor de cada coluna?\n", df_dados.min())
print("\nQual o maior valor?\n", df_dados.max())
print("\nQual a média aritimética?\n", df_dados.mean())
print("\nQual o desvio padrão?\n", df_dados.std())
print("\nQual a mediana?\n", df_dados.median())

print("\nResumo:\n", df_dados.describe())

df_dados.head()

df_uma_coluna = df_dados["idades"]
print(type(df_uma_coluna))
print("Média de idades = ", df_uma_coluna.mean())
df_uma_coluna

colunas = ["nomes", "cpfs"]
df_duas_colunas = df_dados[colunas]
print(type(df_duas_colunas))
df_duas_colunas

Informações do DataFrame:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nomes   5 non-null      object
 1   cpfs    5 non-null      object
 2   emails  5 non-null      object
 3   idades  5 non-null      int64
dtypes: int64(1), object(3)
memory usage: 288.0+ bytes
None

Quantidades de linhas e colunas =  (5, 4)

Tipo de dados:
 nomes     object
cpfs      object
emails    object
idades     int64
dtype: object

Qual o menor valor de cada coluna?
 nomes                Howard
cpfs         111.111.111-11
emails    Nunc@vulputate.ca
idades                   22
dtype: object

Qual o maior valor?
 nomes                                 Peter
cpfs                         555.555.555-55
emails    risus.varius@dictumPhasellusin.ca
idades                                   38
dtype: object

Qual a média aritimética?
 idades    29.2
dtype: float64

Qual o desvio padrão?
 idades    6.220932
dtype: float64

Qual a mediana?
 idades    29.0
dtype: float64

Resumo:
           idades
count   5.000000
mean   29.200000
std     6.220932
min    22.000000
25%    25.000000
50%    29.000000
75%    32.000000
max    38.000000
<class 'pandas.core.series.Series'>
Média de idades =  29.2
<class 'pandas.core.frame.DataFrame'>

<ipython-input-2-668e95bf1601>:19: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print("\nQual a média aritimética?\n", df_dados.mean())
<ipython-input-2-668e95bf1601>:20: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print("\nQual o desvio padrão?\n", df_dados.std())
<ipython-input-2-668e95bf1601>:21: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print("\nQual a mediana?\n", df_dados.median())

    nomes            cpfs
0  Howard  111.111.111-11
1     Ian  222.222.222-22
2   Peter  333.333.333-33
3   Jonah  444.444.444-44
4  Kellie  555.555.555-55