##<b>Estudo Pandas</b><br><i>Parte 04

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/database/fifa19.csv')

df.head(3)

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M

In [ ]:
df_null = df[['ID', 'Name', 'LCB', 'LB']].head(10)
df_null

       ID               Name   LCB    LB
0  158023           L. Messi  47+2  59+2
1   20801  Cristiano Ronaldo  53+3  61+3
2  190871          Neymar Jr  47+3  60+3
3  193080             De Gea   NaN   NaN
4  192985       K. De Bruyne  66+3  73+3
5  183277          E. Hazard  49+3  60+3
6  177003          L. Modrić  71+3  79+3
7  176580          L. Suárez  63+5  66+5
8  155862       Sergio Ramos  87+3  84+3
9  200389           J. Oblak   NaN   NaN

In [ ]:
df_null.isna()

      ID   Name    LCB     LB
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True   True
4  False  False  False  False
5  False  False  False  False
6  False  False  False  False
7  False  False  False  False
8  False  False  False  False
9  False  False   True   True

In [ ]:
df_null.isna().sum()

ID      0
Name    0
LCB     2
LB      2
dtype: int64

In [ ]:
df_null[pd.isna(df_null['LCB'])] # Filtrar linhas missing

       ID      Name  LCB   LB
3  193080    De Gea  NaN  NaN
9  200389  J. Oblak  NaN  NaN

In [ ]:
df_null[df_null['LCB'].notna()] # Filtra quem não tem missing

       ID               Name   LCB    LB
0  158023           L. Messi  47+2  59+2
1   20801  Cristiano Ronaldo  53+3  61+3
2  190871          Neymar Jr  47+3  60+3
4  192985       K. De Bruyne  66+3  73+3
5  183277          E. Hazard  49+3  60+3
6  177003          L. Modrić  71+3  79+3
7  176580          L. Suárez  63+5  66+5
8  155862       Sergio Ramos  87+3  84+3

In [ ]:
df_null.fillna('0')

       ID               Name   LCB    LB
0  158023           L. Messi  47+2  59+2
1   20801  Cristiano Ronaldo  53+3  61+3
2  190871          Neymar Jr  47+3  60+3
3  193080             De Gea     0     0
4  192985       K. De Bruyne  66+3  73+3
5  183277          E. Hazard  49+3  60+3
6  177003          L. Modrić  71+3  79+3
7  176580          L. Suárez  63+5  66+5
8  155862       Sergio Ramos  87+3  84+3
9  200389           J. Oblak     0     0

In [ ]:
# df_null.fillna(df_null.mean(), inplace= True) # Preencher numericos com média/ inplace= True para mudança permanente

In [ ]:
values = {'LCB': '0', 'LB': '999999'}
df_null.fillna(value = values) # Preencher valores nulos com dicionario.

       ID               Name   LCB      LB
0  158023           L. Messi  47+2    59+2
1   20801  Cristiano Ronaldo  53+3    61+3
2  190871          Neymar Jr  47+3    60+3
3  193080             De Gea     0  999999
4  192985       K. De Bruyne  66+3    73+3
5  183277          E. Hazard  49+3    60+3
6  177003          L. Modrić  71+3    79+3
7  176580          L. Suárez  63+5    66+5
8  155862       Sergio Ramos  87+3    84+3
9  200389           J. Oblak     0  999999

In [ ]:
df_null.dropna()

       ID               Name   LCB    LB
0  158023           L. Messi  47+2  59+2
1   20801  Cristiano Ronaldo  53+3  61+3
2  190871          Neymar Jr  47+3  60+3
4  192985       K. De Bruyne  66+3  73+3
5  183277          E. Hazard  49+3  60+3
6  177003          L. Modrić  71+3  79+3
7  176580          L. Suárez  63+5  66+5
8  155862       Sergio Ramos  87+3  84+3

In [ ]:
df_null.dropna(subset= ['LCB']) # Exclui missing apénas presente em 'subset'

       ID               Name   LCB    LB
0  158023           L. Messi  47+2  59+2
1   20801  Cristiano Ronaldo  53+3  61+3
2  190871          Neymar Jr  47+3  60+3
4  192985       K. De Bruyne  66+3  73+3
5  183277          E. Hazard  49+3  60+3
6  177003          L. Modrić  71+3  79+3
7  176580          L. Suárez  63+5  66+5
8  155862       Sergio Ramos  87+3  84+3

In [ ]:
df['Weight'].head()

0    159lbs
1    183lbs
2    150lbs
3    168lbs
4    154lbs
Name: Weight, dtype: object

In [ ]:
df['Weight'].fillna('0lbs', inplace= True)

In [ ]:
teste = df['Weight'].head()
teste[1].replace('lbs', '')

'183'

In [ ]:
def substitui_lbs(value):
  x = value.replace('lbs', '')
  return int(x)

df['Weight_new'] = df['Weight'].apply(substitui_lbs)
df.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,Weight_new
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M,159
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M,183
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M,150
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M,168
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M,154

In [ ]:
df['Wage'].head()

0    €565K
1    €405K
2    €290K
3    €260K
4    €355K
Name: Wage, dtype: object

In [ ]:
def converte_wage(value):
    value_2= value.replace('€', '')
    if 'M' in value_2:
      value_2= value_2.replace('M', '')
      return float(value_2)* 1000000
    elif 'K' in value_2:
      value_2= value_2.replace('K', '')
      return float(value_2)* 1000

df['Wage_Numeric']= df['Wage'].apply(converte_wage)
df.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,Weight_new,Wage_Numeric
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M,159,565000.0
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M,183,405000.0
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M,150,290000.0
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M,168,260000.0
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M,154,355000.0

In [ ]:
df['avg_GK']= (df['GKDiving']+ df['GKHandling']+ df['GKKicking']+ df['GKPositioning']+ df['GKReflexes'])/5
df.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,Weight_new,Wage_Numeric,avg_GK
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M,159,565000.0,10.8
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M,183,405000.0,11.6
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M,150,290000.0,11.8
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M,168,260000.0,88.8
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M,154,355000.0,11.2

In [ ]:
df['Age_Class'] = np.where(df['Age'] > 30, 'Old', 'Young') # Esse campo condicional precisa de "Import numpy as np"
df.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,Weight_new,Wage_Numeric,avg_GK,Age_Class
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,6.0,11.0,15.0,14.0,8.0,€226.5M,159,565000.0,10.8,Old
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,7.0,11.0,15.0,14.0,11.0,€127.1M,183,405000.0,11.6,Old
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,9.0,9.0,15.0,15.0,11.0,€228.1M,150,290000.0,11.8,Young
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,90.0,85.0,87.0,88.0,94.0,€138.6M,168,260000.0,88.8,Young
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,15.0,13.0,5.0,10.0,13.0,€196.4M,154,355000.0,11.2,Young

In [ ]:
df['Age_Class2'] = 'Young'
df.loc[df['Age'] > 30, 'Age_Class2']= 'Old'
df.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,Weight_new,Wage_Numeric,avg_GK,Age_Class,Age_Class2
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,11.0,15.0,14.0,8.0,€226.5M,159,565000.0,10.8,Old,Old
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,11.0,15.0,14.0,11.0,€127.1M,183,405000.0,11.6,Old,Old
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,9.0,15.0,15.0,11.0,€228.1M,150,290000.0,11.8,Young,Young
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,85.0,87.0,88.0,94.0,€138.6M,168,260000.0,88.8,Young,Young
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,13.0,5.0,10.0,13.0,€196.4M,154,355000.0,11.2,Young,Young

### Extras

In [ ]:
# Criar dataframe a partir de clipboards, simplismente copie a tabela e faça:
# df_clipboard = pd.read_clipboard()

In [ ]:
# Usar dados dummies para treinar modelos:
pd.util.testing.makeDataFrame()

                   A         B         C         D
yzfHhz2DtX  0.419213  0.292328 -2.145892 -0.789018
7AAY422WSp -0.327768 -0.707684  0.342540  0.520885
WzUpOWMKgl -0.413093 -1.659513 -0.726411 -1.449523
PEKFbQsw8P -1.791168 -0.340858  0.859157  0.250713
eA1UKfYYJh  0.191408  0.450693  0.474229 -0.510115
m8PloTThg9  0.190607 -0.287294  0.413840 -0.016035
o3jaao7mMK  1.039335  1.302198 -1.028167 -0.585575
XbNVzVxuUj -0.826974 -0.951929  0.093927 -0.912096
sRZx5GTEFZ  0.693362 -1.254100  0.795587  0.899849
Il0Y9gg2jw  1.330254 -0.404990  1.219095 -0.008150
rYcMVnenRU -0.228681  1.378414 -0.274498  1.528467
Z7cheRqsKh  0.845862 -1.856209  0.156131  0.324466
udyzgrpwAD  0.081471  0.004644 -0.819855 -0.742297
dOKXRmzwhj  0.722048  1.197230  1.969972 -0.495506
znTKWrcjMO  0.626188  0.146323 -1.493046 -0.212068
XY5OZ17j0p  1.270122  0.257432 -0.388947  0.579037
eiLNxOCRVt -0.154722 -0.865873  0.132540  0.137466
47z8KizqgH -0.226469 -0.350973 -0.102534  0.061889
VoVyqQjzPn  0.259418  0.262522  0.684983 -1.137424
40jod9LpW0 -0.043182 -1.079405  0.362886  0.499959
QtPC8htbxa -1.177150  1.203351  0.553436  1.076386
T64rsFfHZ6  0.259501 -1.083806  1.412452 -0.780322
uIf587sY9r -0.333973 -0.854951 -0.418777 -2.743266
sgGf98EYA9 -0.085928 -1.019413  0.672100 -0.279484
Z2E0yHsDkA  1.978057  2.311399  0.774564  0.979999
6z9Vtw7sff -2.005184  0.657071  0.048775 -0.592676
aP4J4OOvzO -0.468786 -0.260662  2.324398  0.404911
wIJvsAQlRn  0.599230 -1.412239 -1.536954 -2.108433
bSxBncRdgK  0.099527  1.832879  3.222279 -0.322203
h1BnFVh8Ri  1.387681 -0.901342 -1.736703  0.152213