## <b>Aprendizado de Máquina</b><br>
Modelo de <i>Regressão</i><br><br>
Pré-visualização dos dados:

In [2]:
import pandas as pd
df= pd.read_csv("https://raw.githubusercontent.com/redsonlopez/ds/main/datasets/housing_prices_train.csv")
df.head(3)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500

Separação dos dados de treino e teste:

In [3]:
from sklearn.model_selection import train_test_split
features= ['LotArea', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'FullBath', 'BedroomAbvGr', 'TotRmsAbvGrd']
X= df[features]
y= df.SalePrice
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size= 0.20, random_state=1)

Treino e teste do modelo:

In [4]:
from sklearn.ensemble import RandomForestRegressor
rf= RandomForestRegressor()
rf.fit(X_train, y_train)
predicted = rf.predict(X_val)

Métricas para calcular o desempenho do modelo:

In [5]:
from sklearn.metrics import mean_absolute_error, r2_score
print("Mean absolute error: %.0f"%mean_absolute_error(y_val, predicted)) # Quanto menor o valor do erro, melhor.
print("Forecast coefficient: %.2f" %r2_score(y_val, predicted)) # Capacidade de capturar a variação nos valores reais da variável de destino.

Mean absolute error: 22423
Forecast coefficient: 0.85